### ISSUE TITLE
'common_icinga2_master_zone_net_list' is undefined

### ISSUE THREAD

**Issue by nnnms** [nbw74/roles#1]
ansible-playbook ../playbooks/vhost.yml fails with error

```
TASK [vhost : determine if prod circuit] *************************************************
fatal: [host.name]: FAILED! => {"msg": "'common_icinga2_master_zone_net_list' is undefined"}
```
inventory/hosts:
```
[mygroup]
host.name
```
inventory/host_vars/host.name.yml:

```
---
php_remi_version: 7.2

vhost_backend: "php-fpm"

vhost:

- name: host.name
  fpm:
    port: 9000
  webroot: "www/public"

...
```
